### ISSUE TITLE
why flake8 doesn't work?

### ISSUE THREAD

**Issue by HuaYishu** [sublimelsp/LSP-pylsp#110]
Here is my pylsp configuration:
```json
{
    "pylsp.configurationSources": ["flake8"],
    "pylsp.plugins.flake8.enabled": true,
    "pylsp.plugins.pycodestyle.enabled": false,
}
```
And I try to restart sublime several times, however, it just doesn't work and linter is stiil pycodestyle.

But, what is strange is that the option "python-binary" can work when I rewrite it. So, I think the user configuration on linter written by user seems to be unable to cover the defualt.

**Comment by rchl** [comment]
Where did you place those options? Doesn't look like it's using expected structure. Follow the structure of default settings.

**Comment by HuaYishu** [comment]
You're right. Those linter options should be placed in settings. Thanks a lot.
