### ISSUE TITLE
Upload package to Package Control?

### ISSUE THREAD

**Issue by NoahGorny** [sublimelsp/LSP-pylsp#13]
This will make the installation so much easier

**Comment by rwols** [comment]
It's an ST4 package, and I am hesitant to upload it until there is a public release for ST4.

**Comment by kevinvalk** [comment]
Public release is here, would love this in package control :)

**Comment by rchl** [comment]
I'd probably switch to the https://github.com/python-lsp/python-lsp-server fork before releasing it since `pyls` seems kinda dead.

Also, did you guys consider LSP-pyright instead? The general opinion is that it's superior to this one when it comes to language support. It doesn't support linting and plugins stuff though.

**Comment by StabbarN** [comment]
How do I install this package? I've only used Package Control.

**Comment by TheSecEng** [comment]
@StabbarN within your Packages directory you will need to run `git clone https://github.com/sublimelsp/LSP-pyls.git` and there you have it

Your packages directory can be found by running

```python
sublime.packages_path()
```

In your sublime console

**Comment by StabbarN** [comment]
@TheSecEng Thank you! It worked perfectly. I didn't even have to restart sublime.

**Comment by rwols** [comment]
Yeah, we worked pretty hard on seamless installation.

**Comment by reagle** [comment]
Perhaps put this in the readme?

> git clone https://github.com/sublimelsp/LSP-pyls.git

**Comment by rchl** [comment]
I'm working on switching out pyls for pylsp in https://github.com/sublimelsp/LSP-pyls/pull/23

Once that is done, will publish `LSP-pylsp` to package control.

**Comment by rchl** [comment]
Done.

**Comment by reagle** [comment]
Thank you. I'm new to PLS and just updated to the LSP-pylsp in package control. I'm able to disable pycodestyle and mccabe with the following, but I don't understand isort. First, should it be "pylsp.plugins.pyls_isort.enabled" and second, what does it do? Does it show a warning (I don't see it) or auto-format the code? I've set it to true and don't see either.

     // Settings in here override those in "LSP-pylsp/LSP-pylsp.sublime-settings"
    {
        "settings":
        {
            "pylsp.plugins.pycodestyle.enabled": false,
            "pylsp.plugins.mccabe.enabled": false,
            "pylsp.plugins.pyls_isort.enabled": true,
        }	
    }

**Comment by reagle** [comment]
Actually I can get the isort via `LSP: Format document`, but it's different from running it in the terminal.

isort in the terminal yields:

```
import argparse
import logging
import os
import re
import string
import sys
import time
from collections import namedtuple
from datetime import datetime
from io import StringIO
from subprocess import Popen, call
from xml.etree.ElementTree import Element, ElementTree, SubElement, parse

from dateutil.parser import parse as dt_parse
from lxml import etree as l_etree

import thunderdell as td
from change_case import sentence_case, title_case
# personal utilities
from web_utils import escape_XML, get_HTML, get_JSON, get_text, unescape_XML
```

`LSP: format file` document yields:

```
import argparse
import logging
import os
import re
import string
import sys
import time
from collections import namedtuple
from datetime import datetime
from io import StringIO
from subprocess import Popen, call
from xml.etree.ElementTree import Element, ElementTree, SubElement, parse

import thunderdell as td
from change_case import sentence_case, title_case
from dateutil.parser import parse as dt_parse
from lxml import etree as l_etree

# personal utilities
from web_utils import escape_XML, get_HTML, get_JSON, get_text, unescape_XML

```

**Comment by reagle** [comment]
I'll stop this here, I think there's a confusing interaction between "LSP: Format File" and sublack running in real time.

**Comment by rchl** [comment]
Are you on https://github.com/sublimelsp/LSP-pylsp/releases/tag/2.0.2 ? This includes a fix for issue where `black` would run even when disabled.

**Comment by reagle** [comment]
Hi, yes, 2.0.2 . I have sublack enabled and running (reformats on every save; this is different than LSP) and it seems like there is a difference between it and pylsp_isort. (I don't need isort that often, so I'll just set _isort to false for now).
