### ISSUE TITLE
Mypy does not follow jedi.environment

### ISSUE THREAD

**Issue by notsocafe** [sublimelsp/LSP-pylsp#138]
For instance, when specifying a Poetry virtualenv through `pylsp.plugins.jedi.environment`, Mypy will not use it, and provide completely broken results.

Additionally, native Poetry support (akin to what vim-ale does) would be a great addition.

**Comment by rchl** [comment]
Feel free to discuss it in https://github.com/python-lsp/pylsp-mypy/issues/39

**Comment by rchl** [comment]
A I don't know exactly what you mean about native Poetry support but I'm assuming that this can only work if there is a separate instance of editor started for each project. In ST you can have multiple projects open in a single process instance so I would guess that this is not possible in ST.
