### ISSUE TITLE
In order to use ruff: do I need to install ruff manually? If not where is it installed?

### ISSUE THREAD

**Issue by ardabro** [sublimelsp/LSP-pylsp#156]
I didn't installed ruff, and I don't see it listed by pip3.
But when turned on I'm getting some (not many) complaints about code formatting, like unused variables, too long line etc.
with ruff issue ID like: `ruff(F841)`.
I'm trying to understand what is going on here.
Where is the ruff? How can I configure it (add exemptions, etc...). Or maybe these messages don't come from ruff?

**Comment by rchl** [comment]
The package creates a virtual environment in package storage with all required packages installed there. It doesn't affect your global python.

You configure stuff through LSP-pylsp settings or through linter's own configuration files per linter's documentation.
