### ISSUE TITLE
The prompt of ruff is too far away from the code. Can it follow the code?

### ISSUE THREAD

**Issue by maryjeck** [sublimelsp/LSP-pylsp#157]
![图片](https://github.com/sublimelsp/LSP-pylsp/assets/4252556/cc697c62-8649-42eb-99fb-54ca024a5a2a)

**Comment by rchl** [comment]
You can assign a key binding to open code actions. Check `lsp_code_actions` key binding in `Preferences: LSP Key Bindings` in the command palette.
