### ISSUE TITLE
Is there a way to display an error list? This way, I can quickly locate errors or warnings.

### ISSUE THREAD

**Issue by maryjeck** [sublimelsp/LSP-pylsp#169]
like as anaconda show,or in a hover list

**Comment by rchl** [comment]
You can show the list of all diagnostics in the current file or across all files. See available shortcuts in https://lsp.sublimetext.io/keyboard_shortcuts/

I think that pylsp only reports diagnostics in open files so you won't be able to see all project-wide issues.
