### ISSUE TITLE
Invalid comment in LSP-pylsp.sublime-settings

### ISSUE THREAD

**Issue by StabbarN** [sublimelsp/LSP-pylsp#25]
See https://github.com/sublimelsp/LSP-pylsp/blob/81fabfe5761e92bdcc202cd1f72dec2d9dd4d8b6/LSP-pylsp.sublime-settings#L62

`flake8` is invalid according to
https://github.com/sublimelsp/LSP-pylsp/blob/master/sublime-package.json#L35-L38

Should it be `pyflakes` instead? Flake8 is a wrapper around pyflakes (and more).

**Comment by predragnikolic** [comment]
> The default configuration source is pycodestyle. Change the pylsp.configurationSources setting to ['flake8'] in order to respect flake8 configuration instead.

that sentence is from this README https://github.com/python-lsp/python-lsp-server#configuration

I did a quick check of the python-lsp-server repo and found this
```
python-lsp-server\pylsp\config\config.py

DEFAULT_CONFIG_SOURCES = ['pycodestyle']
sources = self._settings.get('configurationSources', DEFAULT_CONFIG_SOURCES)

---
python-lsp-server\test\plugins\test_flake8_lint.py
 workspace.update_config({"pylsp": {"configurationSources": ["flake8"]}})

```

So I would say that the acceptable values are: `pycodestyle` and `flake8`

**Comment by StabbarN** [comment]
That makes more sense. So https://github.com/sublimelsp/LSP-pylsp/blob/master/sublime-package.json#L37 should be corrected.

**Comment by predragnikolic** [comment]
Yes, feel free to open a PR :)

**Comment by rchl** [comment]
PR was merged.
