### ISSUE TITLE
Cannot disable mypy

### ISSUE THREAD

**Issue by ybbond** [sublimelsp/LSP-pylsp#28]
## Summary

Eventhough `mypy` disabled in `LSP-pylsp` preference, but `mypy` still reproduce cache file and check for errors

## Expected Results

`mypy` disabled if configured so in `LSP-pylsp` preference

## Details

I have explicitly configured so that `mypy` disabled:

```json
// Settings in here override those in "LSP-pylsp/LSP-pylsp.sublime-settings"
{
  "settings": {
    "pylsp.env": {
      "PYTHONPATH": "$sublime_py_files_dir:$packages",
      // "MYPY_PATH": "$sublime_py_files_dir:$packages"
    },
    "pylsp.plugins.mypy-ls.enabled": false,
    "pylsp.plugins.mypy-ls.live_mode": false,
  },
}
```

but when I open any Python files, it still reproduce `.mypy.cache` file and still show mypy errors

![Screenshot of LSP-pylsp mypy error](https://user-images.githubusercontent.com/25895873/120291743-d7e3cb80-c2ed-11eb-947c-0d79f57abcf8.png)

**Comment by rchl** [comment]
There is some weird discrepancy in key naming in mypy_ls. Using `pylsp.plugins.mypy_ls.enabled` (with the underscore) works.

I'll update the settings and schema once https://github.com/Richardk2n/mypy-ls/issues/7 is addressed one way or another.

**Comment by rchl** [comment]
I've released new version with the setting renamed to `pylsp.plugins.mypy_ls.enabled`.
