### ISSUE TITLE
When formatting, the list will become vertical

### ISSUE THREAD

**Issue by thep0y** [sublimelsp/LSP-pylsp#29]
It doesn’t matter what formatter I use. I didn’t have this problem when I used `pyls` before. 

settings:
```json
"pylsp": {
            "selector": "source.python",
            "settings": {
                "plugins": {
                    "yapf.enabled": true,
                    "autopep8.enabled": false
                }
            }
        }
```

yapf config:
```ini
[style]
based_on_style = pep8
column_limit = 248
```

dynamic image:
![apngb-animated](https://user-images.githubusercontent.com/51874567/120322512-0de97580-c317-11eb-9761-18f1361fb342.png)

`yapf` is not working?

**Comment by rchl** [comment]
The structure of the configuration you've posted is not valid.

Look at the default configuration file in `Preferences: LSP-pylsp Settings` and use the same structure for your overrides.

**Comment by rchl** [comment]
BTW. Don't create configuration in `LSP.sublime-settings` if you are using this package. This package has it's own configuration that I've referenced in the previous comment.

**Comment by rchl** [comment]
You should try directly with `yapf` formatter to see if the issue is in this server or with your configuration itself. If it works the same with `yapf` directly then that would indicate that the yapf config might be wrong.

**Comment by thep0y** [comment]
> You should try directly with `yapf` formatter to see if the issue is in this server or with your configuration itself. If it works the same with `yapf` directly then that would indicate that the yapf config might be wrong.

There is no such issue when formatting the same code directly with `yapf`:
<img width="791" alt="2021-06-01 21 05 07" src="https://user-images.githubusercontent.com/51874567/120328081-0e850a80-c31d-11eb-9629-6bf01d617f8b.png">

**Comment by rchl** [comment]
So how does your project structure look like exactly and what's the configuration file name?

Here is how I've tried it and it appears that the configuration is not picked up even when running `yapf` manually:

![Screenshot 2021-06-01 at 15 17 08](https://user-images.githubusercontent.com/153197/120329743-7111e280-c2ec-11eb-8781-638be191d59c.png)

**Comment by thep0y** [comment]
> So how does your project structure look like exactly and what's the configuration file name?

The test code is in a script file, the file name is `test.py`, so the configuration used by the project is the global configuration:
```json
// Settings in here override those in "LSP-pylsp/LSP-pylsp.sublime-settings"
{
    "settings": {
        "pylsp.plugins.autopep8.enabled": false,
        "pylsp.plugins.yapf.enabled": true,
    }
}
```

The `yapf` configuration file path is `$HOME/.config/yapf/style`, and its content is:
```ini
[style]
based_on_style = pep8
column_limit = 248
```

When I use `yapf` to format the code manually, it will pick up the configuration. The following is an animation demonstration:
![output](https://user-images.githubusercontent.com/51874567/120333677-830e7800-c322-11eb-8c30-76f02f5eb5ad.png)

I think `lsp-pylsp` has some problems when calling `yapf`.

**Comment by rchl** [comment]
Well, for me yapf formats it into a column, like in my screenshot. So until we figure that out, I won't be able to look into the possible issue with this server.

**Comment by rchl** [comment]
Actually, my bad. I had trailing comma in the list so that forced it into a column regardless of the length.

**Comment by thep0y** [comment]
> Actually, my bad. I had trailing comma in the list so that forced it into a column regardless of the length.

So, do you think it might be the issue of `lsp-pylsp`?

**Comment by rchl** [comment]
The naming of the black formatter configuration key was wrong so it was enabled and always used instead of yapf. Fix in https://github.com/sublimelsp/LSP-pylsp/pull/30
