### ISSUE TITLE
support for flake8 per-file-ignores

### ISSUE THREAD

**Issue by reagle** [sublimelsp/LSP-pylsp#35]
Hi, I use per-file-ignores, which have recently been added to python-lsp/python-lsp-server/pull/28.  Does anything special have to happen with this plugin to support this feature?

**Comment by rwols** [comment]
I guess the only thing that needs to happen is to upgrade the targeted pylsp version: https://github.com/sublimelsp/LSP-pylsp/blob/master/requirements.txt

**Comment by rchl** [comment]
There was no new release of pylsp made with that fix yet so we have to wait before we can update it.

I've set up dependabot notifications for dependency updates so that we get notified when it's out.

**Comment by rchl** [comment]
Released https://github.com/sublimelsp/LSP-pylsp/releases/tag/2.1.0 with support for this.

Will appear in about two hours from the time this is posted.

**Comment by reagle** [comment]
Thank you. I'm running LSP 1.6.1 and pylsp 2.1.0 but I'm still being shown per-file-ignores warnings that aren't shown in the terminal, where I know they work. Do I need to reconfigure something?

**Comment by rchl** [comment]
There is a new setting for it. Check the release notes.

Out are you saying that it should follow configuration file but doesn't?

**Comment by reagle** [comment]
I wasn't expecting an additional switch, but I set the following and it seems to work: `"pylsp.plugins.flake8.perFileIgnores": true,`

**Comment by rchl** [comment]
It's an array of strings. See description here https://github.com/sublimelsp/LSP-pylsp/blob/ef7da11b9555b013e04d331ea7e6a6d9f976c07f/sublime-package.json#L98

**Comment by reagle** [comment]
I was expecting it to simply respect the existing configuration (e.g., a `.flake8` file in the directory) not to have to respecify it -- leading to duplication bugs.

**Comment by reagle** [comment]
I don't want to re-specify, but if I were too, it would look like this? 

`        "pylsp.plugins.flake8.perFileIgnores": ["emitters.py:E203,E241,E701,E117,W503","biblio_fields.py:E241"],`

**Comment by rchl** [comment]
According to the description, each "ignore" needs to include the file path.

And also, I would expect the configuration file to work regardless whether using the pylsp settings or not.
You probably also have to make sure to include `flake8` in the `configurationSources` option.

BTW. LPS-json will help with suggesting and validating the settings when editing pylsp settings (among others).

**Comment by reagle** [comment]
According to what description and what is the path relative to? Absolute file system? Sublime Text project?

In the top level of my ST project directory I have a `.flake8` file:

    [flake8]
    per-file-ignores =
        formats/emit_biblatex.py:E203,E241,E701,E117,W503
        formats/emit_yaml.py:E203,E241,E701,E117,W503
        biblio/fields.py:E241

I can run flake8 recursively from this directory and check all my files. I don't understand how I would represent the same in `LSP-pylsp.sublime-settings`.

**Comment by rchl** [comment]
I'd suggest asking for details in https://github.com/python-lsp/python-lsp-server/pull/28 or in that repo's issues in general.

**Comment by rchl** [comment]
But I would expect it to be relative to the project root so the same as in `.flake8` file.
