### ISSUE TITLE
What this plugin has problem? you want craete a IDEA?

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-pylsp#39]
![图片](https://user-images.githubusercontent.com/19589872/124642809-da27df80-dec2-11eb-9c32-c9d69048485c.png)
![图片](https://user-images.githubusercontent.com/19589872/124642824-df852a00-dec2-11eb-8597-1ea13d9ca3dc.png)
![图片](https://user-images.githubusercontent.com/19589872/124642861-e9a72880-dec2-11eb-886c-edded1730b1c.png)

**Comment by rchl** [comment]
I have no idea what are you trying to say here.

**Comment by rwols** [comment]
The total size is about 80MB, which is larger than Sublime Text itself. That's because it is installed in a venv. Nothing more we can do :)

**Comment by jingyuexing** [comment]
SO, I uninstall this plugin,and go back old version
```json
"pyls": {
      "command": [
        "pyls"
      ],
      "selector": "source.python",
    }
```

**Comment by rchl** [comment]
What is the issue? If it doesn't work then try uninstalling the package and installing again.

**Comment by jingyuexing** [comment]
> 
> 
> What is the issue? If it doesn't work then try uninstalling the package and installing again.

My problem is not this. I have already installed the Python-language-server on my computer, but the plugin has been reinstalled again. Why not use the existing one?

**Comment by rwols** [comment]
Because you receive auto-updates. All helper packages work like this. It also handles the virtual env for you and it adjusts the %Path% as well so that it uses the executables bundled in the virtual env. All tricky stuff to set up for a lot of users.
