### ISSUE TITLE
Autocomplete trailing symbols issue

### ISSUE THREAD

**Issue by glubbfreund** [sublimelsp/LSP-pylsp#41]
Hi, 
as soon as I  install this package I have an issue with the trailing symbols, see: https://forum.sublimetext.com/t/autocomplete-trailing-symbols/59677/6

EDIT: The issue still persists if I deactivate Jedi Support
Additional Info: The issue also occurs with LSP-pyright

**Comment by rchl** [comment]
It was discussed in https://github.com/sublimelsp/LSP/issues/1795 and appears to not be an issue in this package/server.
