### ISSUE TITLE
Allow to choose a different pylsp executable

### ISSUE THREAD

**Issue by jack1142** [sublimelsp/LSP-pylsp#42]
As in title, I would like to be able to use `pylsp` executable that I have globally installed in my system rather than rely on the one installed in a venv created by LSP-pylsp.

This would allow pylsp plugins to be able to see and use the additional dependencies like mypy plugins, type stubs, and regular python packages that are needed for static analysis.

**Comment by jack1142** [comment]
Turns out I just missed the setting for this - there is a `command` setting in the LSP-pylsp settings that does this.

**Comment by rchl** [comment]
Do you know of any third-party plugins that are not included by default?

There is not much benefit in using this package if you are using your own pylsp anyway. The settings schema will no longer be complete (if you are using some extra plugin), the server won't be automatically maintained. You might just as well create a custom configuration in LSP.sublime-settings.

That said, the `pylsp.plugins.jedi.extra_paths` setting should allow you to expose extra pacakges and stubs.
