### ISSUE TITLE
Unable to find some modules.

### ISSUE THREAD

**Issue by CAPTAIN1947** [sublimelsp/LSP-pylsp#55]
Pylsp is unable to find some modules like the csv and some other external modules.

**Comment by rchl** [comment]
Nobody is gonna be able to help you with this amount of information.

At least run `LSP: Troubleshoot Server` from the Command Palette and provide its output.

**Comment by CAPTAIN1947** [comment]
> Nobody is gonna be able to help you with this amount of information.
> 
> At least run `LSP: Troubleshoot Server` from the Command Palette and provide its output.

Oh!!! Sorry for asking like that. Here's the info I think you will need.

**Comment by rchl** [comment]
And what is the error?
What is the contents of the file.
Where are those modules that are missing installed (globally or in a venv)?

**Comment by CAPTAIN1947** [comment]
> And what is the error?
I don't get any error messages only it shows no autocompletion available.
> Where are those modules that are missing installed (globally or in a venv)?
Yes the modules are installed globally. I mean it doesn't autocomplete any external modules like pygame, pysimplegui and some built-in modules like random and csv. But it completes some built-in modules correctly like time.

**Comment by rchl** [comment]
WFM
![Screenshot 2021-11-25 at 10 26 41](https://user-images.githubusercontent.com/153197/143415148-4ed479e7-5924-482e-88af-16ef29334d22.png)

**Comment by CAPTAIN1947** [comment]
And the external ones? Are they working?

**Comment by CAPTAIN1947** [comment]
![image](https://user-images.githubusercontent.com/87000456/143420304-b98a5a8a-cf66-459f-a78e-2b8eba62783a.png)

**Comment by rchl** [comment]
I haven't tried that but you said `csv` was not working. So is it then?

For external modules, if those are not working, you might have to look for stub files for those. I won't do the research for you but you can start from here https://github.com/pygame/pygame/issues/839

**Comment by CAPTAIN1947** [comment]
I saying that it doesn't completes the name for some built-in modules.
![image](https://user-images.githubusercontent.com/87000456/143420723-4b4250fe-2c43-45ac-8f20-c7bd86099939.png)

**Comment by CAPTAIN1947** [comment]
But for time it does.
![image](https://user-images.githubusercontent.com/87000456/143421064-5c2046db-7c97-4ab6-ab26-caf64029eb29.png)

**Comment by rchl** [comment]
The `LSP: Toggle Log Panel` shows some relevant error when trying to complete `import c`.

```
LSP-pylsp: 2021-11-25 11:14:53,289 CET - ERROR - pylsp_jsonrpc.endpoint - Failed to handle request 43
LSP-pylsp: Traceback (most recent call last):
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/pylsp/plugins/jedi_completion.py", line 311, in resolve_label
LSP-pylsp:     sig = completion.get_signatures()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/api/classes.py", line 582, in get_signatures
LSP-pylsp:     for s in self._get_signatures()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/api/classes.py", line 570, in _get_signatures
LSP-pylsp:     names = convert_names([self._name], prefer_stubs=True)
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 152, in convert_names
LSP-pylsp:     return _python_to_stub_names(names, fallback_to_python=prefer_stubs)
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
LSP-pylsp:     return list(func(*args, **kwargs))
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 126, in _python_to_stub_names
LSP-pylsp:     for x in _python_to_stub_names([n], fallback_to_python=fallback_to_python):
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/utils.py", line 16, in wrapper
LSP-pylsp:     return list(func(*args, **kwargs))
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/gradual/conversion.py", line 132, in _python_to_stub_names
LSP-pylsp:     v = name.get_defining_qualified_value()
LSP-pylsp:   File "/Users/../Package Storage/LSP-pylsp/lib/python3.9/site-packages/jedi/inference/names.py", line 251, in get_defining_qualified_value
LSP-pylsp:     if context.is_module() or context.is_class():
LSP-pylsp: AttributeError: 'NoneType' object has no attribute 'is_module'
```

I would suggest reporting that in https://github.com/python-lsp/python-lsp-server

**Comment by CAPTAIN1947** [comment]
Ok. For now I am switching to pyright. I guess this issue can be closed.

**Comment by rchl** [comment]
Crash fixed in pylsp - https://github.com/python-lsp/python-lsp-server/issues/121

**Comment by CAPTAIN1947** [comment]
Wow. @rchl 
Thanks for fixing this so quickly.
And is the problem with the external modules also linked with this?
I mean the problem that none of the names of the external modules are completed. Its not with pygame only. I have tried some other external modules also but their names are also not completed , like numpy,matplotlib.

**Comment by rchl** [comment]
I don't really know. It seems to be that numpy comes with type hints so it should work and it works in Pyright.

If you'd ask at https://github.com/python-lsp/python-lsp-server then they would most likely help you or maybe even fix it if it's a bug.

**Comment by CAPTAIN1947** [comment]
Ok. I added the path to site-packages manually and now its working.
![image](https://user-images.githubusercontent.com/87000456/143487196-fa46cc98-612e-4d6c-9699-8bb1f8774f99.png)
![image](https://user-images.githubusercontent.com/87000456/143487231-274e5a18-b14d-4147-b60a-1b03ec8a5d80.png)

But there's a new problem so reopening the issue.
After autocompleting the cursor is after the closing bracket. Instead of between the opening and closing ones.
![image](https://user-images.githubusercontent.com/87000456/143487466-fbceb9a1-38ce-4c3b-b648-b315442e3e75.png)

**Comment by CAPTAIN1947** [comment]
> I don't really know. It seems to me that numpy comes with type hints so it should work and it works in Pyright.
> 
> If you'd ask at https://github.com/python-lsp/python-lsp-server then they would most likely help you or maybe even fix it if it's a bug.

Okay.

**Comment by rchl** [comment]
I have filed your latest issue: https://github.com/python-lsp/python-lsp-server/issues/123

(I don't use pylsp, not sure why I care so much ;)).

**Comment by CAPTAIN1947** [comment]
> I have filed your latest issue: [python-lsp/python-lsp-server#123](https://github.com/python-lsp/python-lsp-server/issues/123)
> 
> (I don't even use pylsp, not sure why I care so much ;)).

Oh no. I too created one. Closing it. :(

**Comment by rchl** [comment]
BTW. Just noticed that you can set `"pylsp.plugins.jedi_completion.include_params": false` which will result in completions without the parameters (or parenthesis). Like in LSP-pyright. That's probably better than such broken completions.

**Comment by CAPTAIN1947** [comment]
```(I don't even use pylsp, not sure why I care so much ;)).```
pylsp is really good. And I think its the best for students. pyright gives too much that often we beginners don't need. I only need the autocompletion and the function docs and thats what pylsp gives me. I couldn't even find the option to disable linting in pyright. 
And can you please tell which package you use for the autocompletions?

**Comment by rchl** [comment]
Sounds like LSP-pyright is a better option for you then since it provides what you need plus is much faster.

LSP-pyright has a `python.analysis.typeCheckingMode` option that you can set to `off`.

**Comment by CAPTAIN1947** [comment]
> Sounds like LSP-pyright is a better option for you then since it provides what you need plus is much faster.
> 
> LSP-pyright has a `python.analysis.typeCheckingMode` option that you can set to `off`.

Yes its there but it has no effect. I guess found another bug.

**Comment by rchl** [comment]
It works here. Maybe you've put the setting in a wrong place.

**Comment by CAPTAIN1947** [comment]
Yes perhaps. But anyways I have found a option in the lsp setting for this. Thanks again.

**Comment by rchl** [comment]
Released new version that fixes some of the crashes observed here.
I don't think there is anything left here that is addressable through this package.
