### ISSUE TITLE
How do you ignore certain "errors" (E501 for example)

### ISSUE THREAD

**Issue by Pshemas** [sublimelsp/LSP-pylsp#65]
I'm trying to disable certain errors, like line too long (e501), but can't find any info howto do it. Any help greatly appreciated.

**Comment by rchl** [comment]
Look at the error message to figure which linter the error is coming from. I'm guessing it flake8 in this case so you can google flake8 documentation and figure out how to configure it.

The server also has a `pylsp.plugins.flake8.ignore` option if you prefer to handle that on the server level.
