### ISSUE TITLE
the autocompletion does not work on 3rd party packages

### ISSUE THREAD

**Issue by braindevices** [sublimelsp/LSP-pylsp#67]
for example `import` can have autocompletion on builtin modules such as time, os, etc. However, it does not work on 3rd party packages at all such as pandas, numpy, lxml, etc. The autocompletion on dot also does not work for those packages. Is the expected?

I did:
```
pip3 install python-lsp-server[all]
```
I also installed:
```
pyls-flake8             0.4.0
pyls-isort              0.2.2
pyls-mypy               0.1.8
pylsp-rope              0.1.8
python-lsp-black        1.0.1
```

**Comment by braindevices** [comment]
It looks like it only see packages in `.cache/sublime-text/Package Storage/LSP-pylsp/lib/python3.8/site-packages` Is this expected?

**Comment by braindevices** [comment]
I created a venv, then installed the lxml in that venv, then set the `pylsp.plugins.jedi.environment` to it, then the autocompletion works on lxml. So I guess it is really the path problem. How do I use the system environment instead? `"pylsp.plugins.jedi.environment": "/" does not work neither.`

**Comment by rchl** [comment]
You can extend paths by modifying (appending paths to):
https://github.com/sublimelsp/LSP-pylsp/blob/cad7553508b971c4f0bc077f07e7060099ce6f85/LSP-pylsp.sublime-settings#L26-L32

BTW. No need to install any pylsp/pyls related dependencies. The package installs and maintains those itself in its own storage directory.
