### ISSUE TITLE
hints for base methods

### ISSUE THREAD

**Issue by Pshemas** [sublimelsp/LSP-pylsp#79]
How do you get doc hints when you hover over a basic method (for example .get, .dict, .copy etc)? I can't get it to work. With methods from imports / self written ones I get the desired popover.

With Pyright I get it correctly:
![pyright_hintbubble](https://user-images.githubusercontent.com/6144330/170540889-2a5bad4c-71b2-4e64-8e0b-3443c678c97e.png)

My LSP-pylsp.sublime-settings looks like this:

```
{
    "settings":
    {
        "pylsp.plugins.jedi.environment": "./.venv/"
    }

}


```
\- as I want Pylsp to pick up virtual environment I've set up.
BTW - is there a way to set such things up in some sort of config file  in the project, instead of "global" setting in Sublime config? I really like the way it is done in Pyright via pryrightconfig.json .

I've found setup.cfg, but it seems I can set pycodestyle there (for example ignores), but not venv.

**Comment by rchl** [comment]
It works here with LSP code. This is from pylsp:

![Screenshot 2022-05-31 at 15 52 14](https://user-images.githubusercontent.com/153197/171190112-ad1eaf8e-5837-4a13-aa35-9a43dae94faa.png)

Could be something with your settings or this specific code you are testing on.
Can you provide a small code sample that reproduces and your LSP-pylsp settings?

> BTW - is there a way to set such things up in some sort of config file in the project,

You can set settings per-project: https://lsp.sublimetext.io/guides/client_configuration/#per-project-overrides
I don't think pylsp support configuration file like pyright.

**Comment by rchl** [comment]
Closing due to no response.
Feel free to provide an example and I'll try to look into more.
