### ISSUE TITLE
Add module directories for site-packages

### ISSUE THREAD

**Issue by rwols** [sublimelsp/LSP-pylsp#8]
- Add /usr/local/lib/pythonX.Y/site-packages
- Add ~/.local/lib/pythonX.Y/site-packages
- Windows? How?
- Virtual environments? How?

**Comment by rchl** [comment]
Any of that is still relevant?
 - The stuff in `/usr/local/lib/pythonX.Y/site-packages` is picked up automatically.
 - Virtual environments are documented
 - as for Windows I'm not sure. I'd assume it works too

**Comment by rwols** [comment]
Alright, I’ll take your word for it :)
