### ISSUE TITLE
No expandpath in path variables

### ISSUE THREAD

**Issue by sprat** [sublimelsp/LSP-pylsp#80]
I would like configure the default jedi environment like this:
```json
{
    "settings": {
        "pylsp.plugins.jedi.environment": "~/.virtualenvs/${project_base_name}",
    }
}
```

However, the plugin does not expand "~" into my home directory path. Could an expandpath be added on the settings variables that hold a path? (I don't know how to do that, otherwise I would have filed a pull request)

**Comment by rwols** [comment]
You can use `$home`: https://github.com/sublimelsp/LSP/blob/ed70eb24e70e43f6b2ba77d4ecc300cac78c31a8/plugin/core/sessions.py#L684

**Comment by sprat** [comment]
Oh right, I didn't tried this. Thanks!
