### ISSUE TITLE
How to use pylsp installed in WSL?

### ISSUE THREAD

**Issue by llan-ml** [sublimelsp/LSP-pylsp#81]
To use `pylsp` installed in WSL, we can directly set up a client in `LSP` with `command` set to `["bash.exe", "-c", "absolute_wsl_path_to_pylsp"]`.

However, with this helper package `LSP-pylsp`, if we set `command` to the above value, it does not work. I suppose that the `command` in this package just overrides the corresponding key in `LSP`. How can we use `pylsp` in WSL with this package?

**Comment by rchl** [comment]
The main advantage of using this package is the fact that it maintains the pylsp dependency. If you are not gonna be using that functionality then you might just as well go with manual client configuration, if that works.

That said, overriding `command` should work just fine. If I set it to invalid path then the server fails to start.
