### ISSUE TITLE
Option to input a proxy server?

### ISSUE THREAD

**Issue by jeffworne** [sublimelsp/LSP-pylsp#95]
Hello,

Is there a method to use a proxy in order to download the required Python packages during installation? I'm behind a corporate firewall and can't download from external sources without a proxy bypass.

**Comment by rwols** [comment]
Did you try setting HTTP_PROXY and HTTPS_PROXY in the env dict?

**Comment by jeffworne** [comment]
I solved this by adding the proxy config to the global pip.ini file. From the command-line
`pip.exe config set global.http_proxy http://PROXY_IP:PROXY_PORT`

**Comment by jeffworne** [comment]
> Did you try setting HTTP_PROXY and HTTPS_PROXY in the env dict?

I did, but that didn't seem to help (for some reason). Adding it to the global pip config file worked, though!
